<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.uregina.geometry</groupId>
    <artifactId>geometry-bom</artifactId>
    <version>1.1.0</version>
    <packaging>pom</packaging>
    <name>GeometryLibrary BOM</name>

    <properties>
        <geometry-core.version>1.1.0</geometry-core.version>
        <geometry-utils.version>1.1.0-SNAPSHOT</geometry-utils.version>
        <three-dimensional-shapes.version>1.0.0-SNAPSHOT</three-dimensional-shapes.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.uregina.geometry</groupId>
                <artifactId>geometry-core</artifactId>
                <version>${geometry-core.version}</version>
            </dependency>
            <dependency>
                <groupId>com.uregina.geometry</groupId>
                <artifactId>geometry-utils</artifactId>
                <version>${geometry-utils.version}</version>
            </dependency>
            <dependency>
                <groupId>com.uregina.geometry</groupId>
                <artifactId>three-dimensional-shapes</artifactId>
                <version>${three-dimensional-shapes.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
